name: Maven CI/CD Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Acesso ao .gthub/workflows
    - name: Checkout do repositorio
      uses: actions/checkout@v3
    # Config Java
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    # Rodar teste com Maven
    - name: Run test with Maven
      run: mvn -B test --file pom.xml
